"""add_video_seconds_used_to_licenses

Revision ID: 798466c6dd58
Revises: b618a9ccd7d2
Create Date: 2026-07-25 04:07:15.123984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '798466c6dd58'
down_revision: Union[str, Sequence[str], None] = 'b618a9ccd7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('video_seconds_used', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'video_seconds_used')
    # ### end Alembic commands ###
